apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: insights-system

resources:
  - namespace.yaml
  - etcd.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - apiservice.yaml

images:
  - name: insights-apiserver
    newName: insights-apiserver
    newTag: latest
