apiVersion: v1
kind: Service
metadata:
  name: insights-apiserver
  labels:
    app.kubernetes.io/name: insights
    app.kubernetes.io/component: apiserver
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
  selector:
    app.kubernetes.io/name: insights
    app.kubernetes.io/component: apiserver
