package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// InsightPolicyPhase represents the current phase of an InsightPolicy.
// +kubebuilder:validation:Enum=Active;Suspended;Error
type InsightPolicyPhase string

const (
	// InsightPolicyPhaseActive indicates the policy is actively evaluating resources.
	InsightPolicyPhaseActive InsightPolicyPhase = "Active"
	// InsightPolicyPhaseSuspended indicates the policy is suspended and not evaluating.
	InsightPolicyPhaseSuspended InsightPolicyPhase = "Suspended"
	// InsightPolicyPhaseError indicates the policy has an error (e.g., invalid CEL).
	InsightPolicyPhaseError InsightPolicyPhase = "Error"
)

// ResourceSelector defines criteria for selecting resources to evaluate.
type ResourceSelector struct {
	// APIVersion of the resources to select.
	// +kubebuilder:validation:Required
	APIVersion string `json:"apiVersion"`

	// Kind of the resources to select.
	// +kubebuilder:validation:Required
	Kind string `json:"kind"`

	// Namespaces limits the selection to specific namespaces.
	// If empty, resources from all namespaces are selected.
	// +optional
	Namespaces []string `json:"namespaces,omitempty"`

	// LabelSelector filters resources by labels.
	// +optional
	LabelSelector *metav1.LabelSelector `json:"labelSelector,omitempty"`

	// MatchExpression is an optional CEL expression to further filter resources.
	// The expression has access to 'object' which is the resource being evaluated.
	// Must return a boolean value.
	// +optional
	MatchExpression string `json:"matchExpression,omitempty"`
}

// InsightRule defines a single rule for generating insights.
type InsightRule struct {
	// Name is a unique identifier for this rule within the policy.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern=`^[a-z0-9]([-a-z0-9]*[a-z0-9])?$`
	// +kubebuilder:validation:MaxLength=63
	Name string `json:"name"`

	// Condition is a CEL expression that determines when to create an insight.
	// The expression has access to 'object' which is the resource being evaluated.
	// Must return a boolean value. When true, an insight will be created.
	// +kubebuilder:validation:Required
	Condition string `json:"condition"`

	// Severity of the generated insight.
	// +kubebuilder:validation:Required
	Severity InsightSeverity `json:"severity"`

	// Category of the generated insight.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=64
	Category string `json:"category"`

	// TTLSeconds for the generated insight.
	// A value of 0 means the insight never expires.
	// +optional
	// +kubebuilder:default=0
	TTLSeconds int64 `json:"ttlSeconds,omitempty"`

	// MessageTemplate is a template string for the insight message.
	// Supports {{ cel_expression }} placeholders that will be evaluated
	// against the matched resource.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=512
	MessageTemplate string `json:"messageTemplate"`

	// DescriptionTemplate is a template string for the insight description.
	// Supports {{ cel_expression }} placeholders that will be evaluated
	// against the matched resource.
	// +optional
	DescriptionTemplate string `json:"descriptionTemplate,omitempty"`
}

// InsightRuleStatus contains status information for a specific rule.
type InsightRuleStatus struct {
	// Name of the rule.
	Name string `json:"name"`

	// MatchCount is the number of resources that matched the selector.
	MatchCount int32 `json:"matchCount"`

	// InsightCount is the number of insights generated by this rule.
	InsightCount int32 `json:"insightCount"`

	// Error contains any error message from evaluating this rule.
	// +optional
	Error string `json:"error,omitempty"`
}

// InsightPolicySpec defines the desired state of InsightPolicy.
type InsightPolicySpec struct {
	// Selector defines which resources this policy applies to.
	// +kubebuilder:validation:Required
	Selector ResourceSelector `json:"selector"`

	// Rules defines the list of rules for generating insights.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinItems=1
	Rules []InsightRule `json:"rules"`

	// Suspended indicates whether this policy should stop evaluating.
	// +optional
	// +kubebuilder:default=false
	Suspended bool `json:"suspended,omitempty"`

	// ResyncPeriodSeconds defines how often to re-evaluate all resources.
	// +optional
	// +kubebuilder:default=300
	// +kubebuilder:validation:Minimum=60
	ResyncPeriodSeconds int64 `json:"resyncPeriodSeconds,omitempty"`

	// InsightNamePrefix is used to generate deterministic insight names.
	// If not specified, the policy name is used.
	// +optional
	// +kubebuilder:validation:Pattern=`^[a-z0-9]([-a-z0-9]*[a-z0-9])?$`
	// +kubebuilder:validation:MaxLength=32
	InsightNamePrefix string `json:"insightNamePrefix,omitempty"`

	// InsightNamespace specifies where to create Insights for cluster-scoped
	// target resources. For namespace-scoped targets, Insights are created
	// in the target's namespace. Required when targeting cluster-scoped resources.
	// +optional
	InsightNamespace string `json:"insightNamespace,omitempty"`
}

// InsightPolicyStatus defines the observed state of InsightPolicy.
type InsightPolicyStatus struct {
	// Phase indicates the current phase of the policy.
	// +optional
	Phase InsightPolicyPhase `json:"phase,omitempty"`

	// MatchingResourceCount is the total number of resources matching the selector.
	// +optional
	MatchingResourceCount int32 `json:"matchingResourceCount,omitempty"`

	// SkippedResourceCount is the number of resources skipped due to evaluation errors.
	// +optional
	SkippedResourceCount int32 `json:"skippedResourceCount,omitempty"`

	// TotalInsightCount is the total number of insights generated by this policy.
	// +optional
	TotalInsightCount int32 `json:"totalInsightCount,omitempty"`

	// RuleStatuses contains status information for each rule.
	// +optional
	RuleStatuses []InsightRuleStatus `json:"ruleStatuses,omitempty"`

	// LastEvaluationTime is the timestamp of the last evaluation.
	// +optional
	LastEvaluationTime *metav1.Time `json:"lastEvaluationTime,omitempty"`

	// Conditions represent the latest available observations of the policy's state.
	// +optional
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// ObservedGeneration is the most recent generation observed for this policy.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
}

// +genclient
// +genclient:nonNamespaced
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster
// +kubebuilder:printcolumn:name="Selector",type=string,JSONPath=`.spec.selector.kind`
// +kubebuilder:printcolumn:name="Matching",type=integer,JSONPath=`.status.matchingResourceCount`
// +kubebuilder:printcolumn:name="Insights",type=integer,JSONPath=`.status.totalInsightCount`
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// InsightPolicy defines rules for automatically generating Insights.
type InsightPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   InsightPolicySpec   `json:"spec,omitempty"`
	Status InsightPolicyStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true

// InsightPolicyList contains a list of InsightPolicy.
type InsightPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InsightPolicy `json:"items"`
}
