//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcknowledgeOptions) DeepCopyInto(out *AcknowledgeOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcknowledgeOptions.
func (in *AcknowledgeOptions) DeepCopy() *AcknowledgeOptions {
	if in == nil {
		return nil
	}
	out := new(AcknowledgeOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcknowledgeOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcknowledgementInfo) DeepCopyInto(out *AcknowledgementInfo) {
	*out = *in
	out.By = in.By
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcknowledgementInfo.
func (in *AcknowledgementInfo) DeepCopy() *AcknowledgementInfo {
	if in == nil {
		return nil
	}
	out := new(AcknowledgementInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorReference) DeepCopyInto(out *ActorReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorReference.
func (in *ActorReference) DeepCopy() *ActorReference {
	if in == nil {
		return nil
	}
	out := new(ActorReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignOptions) DeepCopyInto(out *AssignOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.Assignee = in.Assignee
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignOptions.
func (in *AssignOptions) DeepCopy() *AssignOptions {
	if in == nil {
		return nil
	}
	out := new(AssignOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AssignOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignmentInfo) DeepCopyInto(out *AssignmentInfo) {
	*out = *in
	out.By = in.By
	out.To = in.To
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignmentInfo.
func (in *AssignmentInfo) DeepCopy() *AssignmentInfo {
	if in == nil {
		return nil
	}
	out := new(AssignmentInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Insight) DeepCopyInto(out *Insight) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Insight.
func (in *Insight) DeepCopy() *Insight {
	if in == nil {
		return nil
	}
	out := new(Insight)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Insight) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightList) DeepCopyInto(out *InsightList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Insight, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightList.
func (in *InsightList) DeepCopy() *InsightList {
	if in == nil {
		return nil
	}
	out := new(InsightList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InsightList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightMuteMatch) DeepCopyInto(out *InsightMuteMatch) {
	*out = *in
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(PolicyReference)
		**out = **in
	}
	if in.TargetRef != nil {
		in, out := &in.TargetRef, &out.TargetRef
		*out = new(TargetReference)
		**out = **in
	}
	if in.Severity != nil {
		in, out := &in.Severity, &out.Severity
		*out = new(InsightSeverity)
		**out = **in
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightMuteMatch.
func (in *InsightMuteMatch) DeepCopy() *InsightMuteMatch {
	if in == nil {
		return nil
	}
	out := new(InsightMuteMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightMuteRule) DeepCopyInto(out *InsightMuteRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightMuteRule.
func (in *InsightMuteRule) DeepCopy() *InsightMuteRule {
	if in == nil {
		return nil
	}
	out := new(InsightMuteRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InsightMuteRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightMuteRuleList) DeepCopyInto(out *InsightMuteRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InsightMuteRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightMuteRuleList.
func (in *InsightMuteRuleList) DeepCopy() *InsightMuteRuleList {
	if in == nil {
		return nil
	}
	out := new(InsightMuteRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InsightMuteRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightMuteRuleSpec) DeepCopyInto(out *InsightMuteRuleSpec) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightMuteRuleSpec.
func (in *InsightMuteRuleSpec) DeepCopy() *InsightMuteRuleSpec {
	if in == nil {
		return nil
	}
	out := new(InsightMuteRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightMuteRuleStatus) DeepCopyInto(out *InsightMuteRuleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightMuteRuleStatus.
func (in *InsightMuteRuleStatus) DeepCopy() *InsightMuteRuleStatus {
	if in == nil {
		return nil
	}
	out := new(InsightMuteRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightPolicy) DeepCopyInto(out *InsightPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightPolicy.
func (in *InsightPolicy) DeepCopy() *InsightPolicy {
	if in == nil {
		return nil
	}
	out := new(InsightPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InsightPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightPolicyList) DeepCopyInto(out *InsightPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InsightPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightPolicyList.
func (in *InsightPolicyList) DeepCopy() *InsightPolicyList {
	if in == nil {
		return nil
	}
	out := new(InsightPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InsightPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightPolicySpec) DeepCopyInto(out *InsightPolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]InsightRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightPolicySpec.
func (in *InsightPolicySpec) DeepCopy() *InsightPolicySpec {
	if in == nil {
		return nil
	}
	out := new(InsightPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightPolicyStatus) DeepCopyInto(out *InsightPolicyStatus) {
	*out = *in
	if in.RuleStatuses != nil {
		in, out := &in.RuleStatuses, &out.RuleStatuses
		*out = make([]InsightRuleStatus, len(*in))
		copy(*out, *in)
	}
	if in.LastEvaluationTime != nil {
		in, out := &in.LastEvaluationTime, &out.LastEvaluationTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightPolicyStatus.
func (in *InsightPolicyStatus) DeepCopy() *InsightPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(InsightPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightRule) DeepCopyInto(out *InsightRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightRule.
func (in *InsightRule) DeepCopy() *InsightRule {
	if in == nil {
		return nil
	}
	out := new(InsightRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightRuleStatus) DeepCopyInto(out *InsightRuleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightRuleStatus.
func (in *InsightRuleStatus) DeepCopy() *InsightRuleStatus {
	if in == nil {
		return nil
	}
	out := new(InsightRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightSource) DeepCopyInto(out *InsightSource) {
	*out = *in
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(PolicyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightSource.
func (in *InsightSource) DeepCopy() *InsightSource {
	if in == nil {
		return nil
	}
	out := new(InsightSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightSpec) DeepCopyInto(out *InsightSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightSpec.
func (in *InsightSpec) DeepCopy() *InsightSpec {
	if in == nil {
		return nil
	}
	out := new(InsightSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightStatus) DeepCopyInto(out *InsightStatus) {
	*out = *in
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(ActorReference)
		**out = **in
	}
	if in.Acknowledgement != nil {
		in, out := &in.Acknowledgement, &out.Acknowledgement
		*out = new(AcknowledgementInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Snooze != nil {
		in, out := &in.Snooze, &out.Snooze
		*out = new(SnoozeInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Assignment != nil {
		in, out := &in.Assignment, &out.Assignment
		*out = new(AssignmentInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Resolution != nil {
		in, out := &in.Resolution, &out.Resolution
		*out = new(ResolutionInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetExists != nil {
		in, out := &in.TargetExists, &out.TargetExists
		*out = new(bool)
		**out = **in
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.DeleteAt != nil {
		in, out := &in.DeleteAt, &out.DeleteAt
		*out = (*in).DeepCopy()
	}
	if in.MutedBy != nil {
		in, out := &in.MutedBy, &out.MutedBy
		*out = new(MuteRuleReference)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightStatus.
func (in *InsightStatus) DeepCopy() *InsightStatus {
	if in == nil {
		return nil
	}
	out := new(InsightStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MuteRuleReference) DeepCopyInto(out *MuteRuleReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MuteRuleReference.
func (in *MuteRuleReference) DeepCopy() *MuteRuleReference {
	if in == nil {
		return nil
	}
	out := new(MuteRuleReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyReference) DeepCopyInto(out *PolicyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyReference.
func (in *PolicyReference) DeepCopy() *PolicyReference {
	if in == nil {
		return nil
	}
	out := new(PolicyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolutionInfo) DeepCopyInto(out *ResolutionInfo) {
	*out = *in
	out.By = in.By
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolutionInfo.
func (in *ResolutionInfo) DeepCopy() *ResolutionInfo {
	if in == nil {
		return nil
	}
	out := new(ResolutionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolveOptions) DeepCopyInto(out *ResolveOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolveOptions.
func (in *ResolveOptions) DeepCopy() *ResolveOptions {
	if in == nil {
		return nil
	}
	out := new(ResolveOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResolveOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSelector) DeepCopyInto(out *ResourceSelector) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSelector.
func (in *ResourceSelector) DeepCopy() *ResourceSelector {
	if in == nil {
		return nil
	}
	out := new(ResourceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnoozeInfo) DeepCopyInto(out *SnoozeInfo) {
	*out = *in
	out.By = in.By
	in.At.DeepCopyInto(&out.At)
	in.Until.DeepCopyInto(&out.Until)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnoozeInfo.
func (in *SnoozeInfo) DeepCopy() *SnoozeInfo {
	if in == nil {
		return nil
	}
	out := new(SnoozeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnoozeOptions) DeepCopyInto(out *SnoozeOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Until != nil {
		in, out := &in.Until, &out.Until
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnoozeOptions.
func (in *SnoozeOptions) DeepCopy() *SnoozeOptions {
	if in == nil {
		return nil
	}
	out := new(SnoozeOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnoozeOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetReference) DeepCopyInto(out *TargetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetReference.
func (in *TargetReference) DeepCopy() *TargetReference {
	if in == nil {
		return nil
	}
	out := new(TargetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnacknowledgeOptions) DeepCopyInto(out *UnacknowledgeOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnacknowledgeOptions.
func (in *UnacknowledgeOptions) DeepCopy() *UnacknowledgeOptions {
	if in == nil {
		return nil
	}
	out := new(UnacknowledgeOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnacknowledgeOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
