apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: insights-system

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - rbac.yaml

images:
  - name: insights-controller
    newName: insights-controller
    newTag: latest
