apiVersion: v1
kind: ServiceAccount
metadata:
  name: insights-controller
  namespace: insights-system
  labels:
    app.kubernetes.io/name: insights
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: insights
