"use client"

import { useRouter } from "next/navigation"
import { useInsightsByLabel } from "@/hooks/use-insights"
import { InsightsTable } from "@/components/insights/insights-table"
import { ErrorState } from "@/components/shared/error-state"
import type { Insight } from "@/types/insights"
import { Lightbulb } from "lucide-react"

interface PolicyInsightsTabProps {
  policyName: string
}

/**
 * PolicyInsightsTab displays insights generated by a specific policy.
 * Fetches using the label selector: insights.miloapis.com/policy-name={policyName}
 */
export function PolicyInsightsTab({ policyName }: PolicyInsightsTabProps) {
  const router = useRouter()
  const labelSelector = `insights.miloapis.com/policy-name=${policyName}`

  const { data, isLoading, isError, error, refetch } = useInsightsByLabel(labelSelector)

  const handleViewInsight = (insight: Insight) => {
    router.push(`/insights/${insight.metadata.namespace}/${insight.metadata.name}`)
  }

  if (isLoading) {
    return (
      <div className="space-y-3 animate-pulse" aria-label="Loading policy insights">
        {[1, 2, 3].map((i) => (
          <div key={i} className="h-12 rounded-md bg-muted" />
        ))}
      </div>
    )
  }

  if (isError) {
    return (
      <ErrorState
        title="Failed to load policy insights"
        message={error?.message ?? "An error occurred while loading insights for this policy."}
        onRetry={() => refetch()}
      />
    )
  }

  const insights = data?.items ?? []

  if (insights.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <Lightbulb className="h-10 w-10 text-muted-foreground/40 mb-3" />
        <p className="font-medium text-muted-foreground">
          No insights generated by this policy yet.
        </p>
        <p className="text-sm text-muted-foreground mt-1">
          Insights appear here when the policy conditions match target resources.
        </p>
      </div>
    )
  }

  return (
    <InsightsTable
      insights={insights}
      onView={handleViewInsight}
    />
  )
}
